server:
  port: 3001

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: medicine-service
          uri: lb://medicine-service
          predicates:
            - Path=/api/medicines/**, /api/skus/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**, /api/customers/**, /api/addresses/**, /api/payments/**, /api/audit-logs/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3006"
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:3000/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:Medicine$SecretKey2024!VeryLongAndSecure}

management:
  endpoints:
    web:
      exposure:
        include: health, info
